version: 2

jobs:
  sbcl:
    docker:
      - image: bnmcgn/warflagger-test:0.0.6
      - image: ipfs/go-ipfs:v0.10.0-rc1
      - image: cimg/postgres:9.6.22
        environment:
        - POSTGRES_USER=circleci
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=test_opinions

    environment:
      LISP: sbcl-bin
    steps:
      - checkout
      # This is the only way CircleCI allows setting environmental variables accross steps
      #- run:
          #name: Setup Environment Variables
          #command: |
          #  echo "export PATH=$HOME/.roswell/bin:$PATH" >> $BASH_ENV

      - run: echo $LISP

      - run:
          command: |
            git clone https://github.com/bnmcgn/cl-react quicklisp/local-projects/cl-react
            git clone https://github.com/bnmcgn/clack-pretend.git quicklisp/local-projects/clack-pretend
            git clone https://github.com/bnmcgn/clath.git quicklisp/local-projects/clath
            git clone https://github.com/bnmcgn/cljwt.git quicklisp/local-projects/cljwt
            git clone https://github.com/bnmcgn/gadgets.git quicklisp/local-projects/gadgets
            git clone https://github.com/bnmcgn/proto.git quicklisp/local-projects/proto
            git clone https://github.com/bnmcgn/ps-gadgets.git quicklisp/local-projects/ps-gadgets
            git clone https://github.com/bnmcgn/sql-stuff.git quicklisp/local-projects/sql-stuff
            git clone https://github.com/bnmcgn/thing-lister.git quicklisp/local-projects/thing-lister
            git clone https://github.com/bnmcgn/userfig.git quicklisp/local-projects/userfig
            git clone https://github.com/bnmcgn/webhax.git quicklisp/local-projects/webhax
            git clone https://github.com/bnmcgn/liql.git quicklisp/local-projects/liql
            git clone https://github.com/bnmcgn/ps-lib-tool.git quicklisp/local-projects/ps-lib-tool
            git clone https://github.com/bnmcgn/reacl.git quicklisp/local-projects/reacl
            git clone https://github.com/bnmcgn/paren6.git quicklisp/local-projects/paren6
            git clone https://github.com/bnmcgn/flaglib.git quicklisp/local-projects/flaglib
            git clone https://github.com/bnmcgn/clerk.git quicklisp/local-projects/clerk

            cp src/local-settings-template.lisp src/local-settings.lisp

      - run:
          command: |
            pip install --user pattern
            pip install --user beautifulsoup4
            pip install --user PyPDF2
            pip install --user readability-lxml

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run: sbcl --script /tmp/quicklisp.lisp

      - run:
          command: |
            psql -h 127.0.0.1 -d 'test_opinions' -c "create user ben with password 'test_password';"
            psql -h 127.0.0.1 -d 'test_opinions' -c "create user postgres with password 'test_password';"
            #psql -h 127.0.0.1 -c 'create database test_opinions;' -U postgres 
            psql -h 127.0.0.1 -d 'test_opinions' -c 'grant all privileges on database test_opinions to ben;'
            psql -h 127.0.0.1 -d 'test_opinions' -1 -f src/opinions.schema.sql

      #- run: ros install warflagger # Because quicklisp on SBCL on CircleCI doesn't install smoothly 
      #- run: ros install ci-utils
      #- run: ros install prove # for run-prove

      - run:
          command: |
            sbcl --no-sysinit --disable-debugger --end-top-level-options \
            --eval "(progn
                     (ql:quickload 'test-warflagger)
                     (if (print (test-warflagger:test-warflagger))
                         (uiop:quit 0)
                         (uiop:quit 1)))"

workflows:
  version: 2
  run_tests:
    jobs:
      - sbcl
  
