;;;; package.lisp

(defpackage #:warflagger
  (:use #:cl #:wf/local-settings #:wf/text-extract #:sql-stuff #:clsql
	#:gadgets #:alexandria #:anaphora #:kebab #:webhax #:cl-postgres #:liql)
  (:export
   #:opinion-ids-for-rooturl
   #:opinion-tree-for-rooturl
   #:controversial-p
   #:get-rooturl
   #:get-rooturl-id
   #:get-opinion-peers
   #:find/store-root-url
   #:make-rooturl-real
   #:rooturl-real-p
   #:get-rooturl-by-id
   #:get-rooturl-for-url
   #:all-rooturls
   #:rooturl-p
   #:get-author-data
   #:opinion-from-db-row
   #:opinion-by-id
   #:get-local-user-id
   #:find-author-id
   #:user-lister
   #:get-author-representation
   #:find-excerpt-position
   #:create-textdata
   #:*flag-categories*
   #:*flag-labels*
   #:*vote-ranges*
   #:*flag-types-source*
   #:author-representation-from-row
   #:warstats-for-target
   #:get-ranked-rootids
   #:opinion-tree-for-target
   #:for-rooturl-mixin
   #:insert-new-author
   #:save-opinion-from-user
   #:author-lister
   #:author-identification-from-row
   #:get-author-identification
   #:opinion-exists-p
   #:opinion-text-server
   #:get-looks
   #:set-look
   #:make-user-url
   #:get-local-user-from-id
   #:opinion-effect
   #:*opinion-effect-cache*
   #:generate-rooturl-warstats
   #:if-production
   #:when-production
   #:unless-production
   #:delete-opinion
   #:get-target-id-from-url
   #:grab-links
   #:save-new-references
   #:*flag-colors*
   #:make-warstats-path
   #:make-warstats-url
   #:write-all-rootid-warstats
   #:*direction-colors*
   #:create-badges-for-rootid
   #:redraw-all-badges
   #:write-all-warstats
   #:make-opinion-url
   #:make-rootid-url
   #:make-missing-rootid-url
   #:make-wf-url-for-url
   #:*warstats-path-types*
   #:cluster-discussions
   #:*flag-category-keys*
   #:*default-vote*
   #:url-p
   #:bulk-enter-file
   #:target-replies
   #:if-travis
   #:when-travis
   #:unless-travis
   #:tree-address
   #:target-seek-server))

