;;;; package.lisp

(defpackage #:warflagger
  (:use #:cl #:wf/local-settings #:warflagger-core #:wf/text-extract #:sql-stuff #:clsql
        #:gadgets #:alexandria #:anaphora #:kebab #:webhax #:cl-postgres #:liql)
  (:shadowing-import-from #:wf/local-settings #:*ssl-key-file*)
  (:export
   #:opinion-ids-for-rooturl
   #:opinion-tree-for-rooturl
   #:controversial-p
   #:get-rooturl
   #:get-rooturl-id
   #:get-opinion-peers
   #:find/store-root-url
   #:make-rooturl-real
   #:rooturl-real-p
   #:get-rooturl-by-id
   #:get-rooturl-for-url
   #:all-rooturls
   #:rooturl-p
   #:get-author-data
   #:opinion-from-db-row
   #:opinion-by-id
   #:get-local-user-id
   #:find-author-id
   #:user-lister
   #:get-author-representation
   #:find-excerpt-position
   #:create-textdata
   #:*flag-categories*
   #:*flag-labels*
   #:*vote-ranges*
   #:*flag-types-source*
   #:author-representation-from-row
   #:warstats-for-target
   #:get-ranked-rootids
   #:opinion-tree-for-target
   #:for-rooturl-mixin
   #:insert-new-author
   #:save-opinion-from-user
   #:author-lister
   #:author-identification-from-row
   #:get-author-identification
   #:opinion-exists-p
   #:opinion-text-server
   #:get-looks
   #:set-look
   #:make-user-url
   #:get-local-user-from-id
   #:opinion-effect
   #:*opinion-effect-cache*
   #:generate-rooturl-warstats
   #:if-production
   #:when-production
   #:unless-production
   #:delete-opinion
   #:get-target-id-from-url
   #:grab-links
   #:save-new-references
   #:*flag-colors*
   #:make-warstats-path
   #:make-warstats-url
   #:write-all-rootid-warstats
   #:*direction-colors*
   #:write-all-warstats
   #:make-opinion-url
   #:make-rootid-url
   #:make-missing-rootid-url
   #:make-wf-url-for-url
   #:*warstats-path-types*
   #:cluster-discussions
   #:*flag-category-keys*
   #:*default-vote*
   #:url-p
   #:bulk-enter-file
   #:target-replies
   #:tree-address
   #:warstats-url-server
   #:target-seek-server
   #:discussion-tree-for-root
   #:order-discussions-by-most-recent-opinion
   #:discussion-roots
   #:get-target-id
   #:question-opinion-p
   #:text-server-dispatcher
   #:opinion-for-location
   #:previous-break
   #:next-break
   #:get-target-text
   #:get-headline-for-url
   #:make-author-url
   #:deserialize-opinion-from-stream
   #:get-ipfs-hash-from-url
   #:*opinion-store*
   #:iid
   #:opinion
   #:opinion-with-iid
   #:opinion-text
   #:extended-opinion-p
   #:extended-opinion
   #:opinion-with-iid-p
   #:opinion-p
   #:iid-p
   #:list-of-type
   #:list-of-type-p
   #:recognized-flag-p
   #:known-flags
   #:make-ballot-box
   #:ballot-box-empty-p
   #:apply-ballot-box-to-warstats
   #:ballot-box-totals
   #:score-vast-majority-p
   #:score-controversy
   #:cast-vote!
   #:merge-ballot-boxes
   #:merge-with-inverted-ballot-boxes
   #:merge-ballot-boxes!
   #:merge-with-inverted-ballot-boxes!
   #:iid-tree-address
   #:iid-tree-address-p
   #:opinion-store
   #:opinion-store-p
   #:iid-opinion-tree
   #:score-script
   #:is-author-initialized
   #:initialize-author
   #:save-opinion
   #:opinion-reference
   #:not-found))

